# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='contract_docs/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Partial', 'Partial'), ('Verified', 'Verified'), ('Damaged', 'Damaged')], default='Verified', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('terms', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
