# Generated by Django 4.2.17 on 2026-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_contract_created_at_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='ordered_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='received_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Pending', 'Pending'), ('Received', 'Received'), ('Partial', 'Partial'), ('Verified', 'Verified'), ('Damaged', 'Damaged')], db_index=True, default='Pending Verification', max_length=50),
        ),
    ]
