# Generated by Django 5.1.15 on 2026-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='verified_by_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
