# Generated by Django 5.1.15 on 2026-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_goodsreceipt_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='ordered_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='received_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Pending', 'Pending'), ('Received', 'Received'), ('Partial', 'Partial'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Damaged', 'Damaged')], db_index=True, default='Pending Verification', max_length=50),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='verified_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
