# Generated by Django 5.2.17 on 2026-09-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0003_initial'),
        ('payment_management', '0003_initial'),
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoice_management.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vendor_management.vendor'),
        ),
    ]
