# Generated by Django 5.1.15 on 2026-09-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0004_alter_invoice_created_at_alter_invoice_due_date_and_more'),
        ('payment_management', '0004_alter_payment_created_at_alter_payment_payment_date_and_more'),
        ('vendor_management', '0002_alter_vendor_created_at_alter_vendor_risk_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoice_management.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Online Bank Transfer', 'Online Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI'), ('Cash on Hand', 'Cash on Hand'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('NEFT / RTGS Corporate Treasury', 'NEFT / RTGS Corporate Treasury'), ('Wire', 'Wire'), ('Credit Card', 'Credit Card'), ('Check', 'Check'), ('Cash', 'Cash')], db_index=True, default='Bank Transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vendor_management.vendor'),
        ),
    ]
