# Generated by Django 5.2.17 on 2026-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0005_payment_processed_by_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='processed_by',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Wire', 'Wire'), ('Credit Card', 'Credit Card'), ('Check', 'Check'), ('MOCK', 'Mock Payment (Simulation)')], default='Bank Transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('MOCK_SUCCESS', 'Mock Payment Success'), ('MOCK_FAILED', 'Mock Payment Failed')], default='Pending', max_length=20),
        ),
    ]
