# Generated by Django 5.1.15 on 2026-10-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0005_payment_payment_proof_payment_vendor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Online Bank Transfer', 'Online Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI'), ('Cash on Hand', 'Cash on Hand'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Wire', 'Wire'), ('Credit Card', 'Credit Card'), ('Check', 'Check'), ('Cash', 'Cash'), ('NEFT/RTGS/IMPS', 'NEFT/RTGS/IMPS')], db_index=True, default='Online Bank Transfer', max_length=60),
        ),
    ]
