# Generated by Django 5.2.17 on 2026-09-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0006_add_mock_payment_method_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('PAID', 'Paid'), ('SUCCESS', 'Payment Success'), ('Failed', 'Failed'), ('MOCK_SUCCESS', 'Mock Payment Success'), ('MOCK_FAILED', 'Mock Payment Failed')], default='Pending', max_length=20),
        ),
    ]
