# Generated by Django 5.1.15 on 2026-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Online Bank Transfer', 'Online Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI'), ('Cash on Hand', 'Cash on Hand'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Wire', 'Wire'), ('Credit Card', 'Credit Card'), ('Check', 'Check'), ('Cash', 'Cash'), ('NEFT/RTGS/IMPS', 'NEFT/RTGS/IMPS'), ('MOCK', 'Mock Payment (Simulation)')], db_index=True, default='Online Bank Transfer', max_length=60),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('PAID', 'Paid'), ('SUCCESS', 'Payment Success'), ('Failed', 'Failed'), ('MOCK_SUCCESS', 'Mock Payment Success'), ('MOCK_FAILED', 'Mock Payment Failed')], db_index=True, default='Pending', max_length=20),
        ),
    ]
