# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_days', models.PositiveIntegerField(default=7)),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('terms_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='quotation_attachments/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Expired', 'Expired'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='rfq_attachments/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
