# Generated by Django 5.2.17 on 2026-09-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request_management', '0002_initial'),
        ('rfq_management', '0001_initial'),
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='vendor_management.vendor'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='invited_vendors',
            field=models.ManyToManyField(related_name='invited_rfqs', to='vendor_management.vendor'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='request_management.purchaserequest'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfq_management.rfq'),
        ),
    ]
