# Generated by Django 5.1.15 on 2026-09-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0003_purchaserequest_extra_fields_and_more'),
        ('rfq_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='request_management.purchaserequest'),
        ),
    ]
