# Generated by Django 4.2.17 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq_management', '0003_alter_rfq_purchase_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], db_index=True, default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Expired', 'Expired'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=20),
        ),
    ]
