# Generated by Django 4.2.17 on 2026-09-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq_management', '0004_alter_quotation_created_at_alter_quotation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Evaluation', 'Under Evaluation'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], db_index=True, default='Submitted', max_length=20),
        ),
    ]
