# Generated by Django 5.1.15 on 2026-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq_management', '0005_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_rate',
            field=models.DecimalField(db_index=True, decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
