# Generated by Django 5.1.15 on 2026-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq_management', '0006_quotation_extra_fields_quotation_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
