# Generated by Django 5.2.17 on 2026-09-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEAM_LEAD', 'Team Lead'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin'), ('VENDOR', 'Vendor')], default='EMPLOYEE', max_length=20),
        ),
    ]
