# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending Match', 'Pending Match'), ('Matched', 'Matched'), ('Exception', 'Exception'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Pending Match', max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_matched', models.BooleanField(default=False)),
                ('variance_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
