# Generated by Django 5.2.17 on 2026-09-10 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_management', '0002_initial'),
        ('procurement', '0001_initial'),
        ('vendor_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vendor_management.vendor'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='procurement.goodsreceipt'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='invoice_management.invoice'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='threewaymatch',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
