# Generated by Django 4.2.17 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending Match', 'Pending Match'), ('Matched', 'Matched'), ('Exception', 'Exception'), ('Approved', 'Approved'), ('Paid', 'Paid')], db_index=True, default='Pending Match', max_length=20),
        ),
        migrations.AlterField(
            model_name='threewaymatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='threewaymatch',
            name='is_matched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
