# Generated by Django 5.1.15 on 2026-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0004_alter_invoice_created_at_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_manager_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verified_by_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
