# Generated by Django 5.1.15 on 2026-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0005_invoice_is_manager_verified_invoice_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reject_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending Match', 'Pending Match'), ('Matched', 'Matched'), ('Exception', 'Exception'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], db_index=True, default='Pending Match', max_length=20),
        ),
    ]
