# Generated by Django 5.1.15 on 2026-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='flow_type',
            field=models.CharField(choices=[('A', 'Flow A'), ('B', 'Flow B')], default='A', max_length=5),
        ),
    ]
