# Generated by Django 5.2.17 on 2026-09-19 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_manager_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='assigned_team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_team_lead_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='current_approval_level',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TEAM_LEAD', 'Team Lead'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin'), ('COMPLETED', 'Completed'), ('NONE', 'None')], default='TEAM_LEAD', max_length=40),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='current_stage',
            field=models.IntegerField(choices=[(0, 'Create Request'), (1, 'Team Lead Review'), (2, 'Manager Approval'), (3, 'Finance Approval'), (4, 'Admin Approval'), (5, 'RFQ Sent'), (6, 'Vendor Quotes Received'), (7, 'Product Order'), (8, 'Delivery'), (9, 'Invoice'), (10, 'Payment')], default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_id',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TEAM_LEAD_REVIEW', 'Team Lead Review'), ('MANAGER_REVIEW', 'Manager Review'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_RECOMMENDED', 'Finance Recommended'), ('FINANCE_REVIEW', 'Finance Review'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('Pending', 'Pending (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Returned', 'Returned (Legacy)'), ('In Procurement', 'In Procurement (Legacy)'), ('Completed', 'Completed (Legacy)')], db_index=True, default='TEAM_LEAD_REVIEW', max_length=40),
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='reason_type',
            field=models.CharField(choices=[('REJECT', 'Rejection Reason'), ('RECOMMEND', 'Recommendation/Escalation Reason'), ('SEND_BACK', 'Send Back Reason')], default='REJECT', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SEND_BACK', 'Sent Back'), ('RESUBMIT', 'Resubmitted'), ('RECOMMEND_FINANCE', 'Recommended to Finance')], max_length=30)),
                ('user_role', models.CharField(max_length=20)),
                ('previous_status', models.CharField(max_length=40)),
                ('new_status', models.CharField(max_length=40)),
                ('comments', models.TextField(blank=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('budget_available', models.BooleanField(default=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='request_management.purchaserequest')),
            ],
            options={
                'verbose_name': 'Approval History Record',
                'verbose_name_plural': 'Approval History Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
