# Generated by Django 4.2.17 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0003_purchaserequest_extra_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='decision',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RECOMMEND', 'Recommend to Next Authority'), ('RETURN', 'Return to Team Lead')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='role',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='current_stage',
            field=models.IntegerField(choices=[(0, 'Create Request'), (1, 'Manager Approval'), (2, 'Finance Approval'), (3, 'Admin Approval'), (4, 'RFQ Sent'), (5, 'Vendor Quotes Received'), (6, 'Product Order'), (7, 'Delivery'), (8, 'Invoice'), (9, 'Payment')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], db_index=True, default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned'), ('In Procurement', 'In Procurement'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
