# Generated by Django 5.2.17 on 2026-09-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0003_purchaserequest_approved_amount_and_more'),
        ('request_management', '0003_purchaserequest_extra_fields_and_more'),
        ('request_management', '0004_alter_approvalstep_created_at_and_more'),
    ]

    operations = [
    ]
