# Generated by Django 5.2.17 on 2026-09-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0004_merge_20260921_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SEND_BACK', 'Sent Back'), ('RESUBMIT', 'Resubmitted'), ('RECOMMEND_FINANCE', 'Recommended to Finance'), ('FINANCE_APPROVE', 'Finance Approved'), ('FINANCE_REJECT', 'Finance Rejected'), ('ADMIN_APPROVE', 'Admin Approved'), ('ADMIN_REJECT', 'Admin Rejected'), ('ADMIN_RETURN', 'Admin Returned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TEAM_LEAD_REVIEW', 'Team Lead Review'), ('MANAGER_REVIEW', 'Manager Review'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_RECOMMENDED', 'Finance Recommended'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('Pending', 'Pending (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Returned', 'Returned (Legacy)'), ('In Procurement', 'In Procurement (Legacy)'), ('Completed', 'Completed (Legacy)')], db_index=True, default='TEAM_LEAD_REVIEW', max_length=40),
        ),
    ]
