# Generated by Django 5.1.15 on 2026-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0004_alter_approvalstep_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='renewal_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_operation',
            field=models.CharField(default='CREATE', max_length=50),
        ),
    ]
