# Generated by Django 5.2.17 on 2026-09-23 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0005_alter_approvalhistory_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='budget_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='business_requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='confirmed_by_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='current_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='existing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='finance_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=40),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_type',
            field=models.CharField(blank=True, default='Renewal', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='required_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='software_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('RESEARCH_SAVED', 'Research Saved'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SEND_BACK', 'Sent Back'), ('RESUBMIT', 'Resubmitted'), ('RECOMMEND_FINANCE', 'Recommended to Finance'), ('FINANCE_APPROVE', 'Finance Approved'), ('FINANCE_REJECT', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('ADMIN_APPROVE', 'Admin Approved'), ('ADMIN_REJECT', 'Admin Rejected'), ('ADMIN_RETURN', 'Admin Returned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='current_stage',
            field=models.IntegerField(choices=[(1, 'Request Created'), (2, 'Manager Review'), (3, 'Manager Research'), (4, 'Pre-Estimation Completed'), (5, 'Manager Approved'), (6, 'Finance Review'), (7, 'Finance Approved'), (8, 'Payment Completed'), (9, 'Team Lead Confirmation'), (10, 'Request Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TEAM_LEAD_SUBMITTED', 'Team Lead Submitted'), ('TEAM_LEAD_REVIEW', 'Team Lead Review'), ('MANAGER_REVIEW', 'Manager Review'), ('MANAGER_RESEARCHING', 'Manager Researching'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_RECOMMENDED', 'Finance Recommended'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('Pending', 'Pending (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Returned', 'Returned (Legacy)'), ('In Procurement', 'In Procurement (Legacy)')], db_index=True, default='TEAM_LEAD_REVIEW', max_length=40),
        ),
        migrations.CreateModel(
            name='ManagerResearchEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_pricing', models.TextField(blank=True)),
                ('renewal_pricing', models.TextField(blank=True)),
                ('upgrade_pricing', models.TextField(blank=True)),
                ('available_plans', models.TextField(blank=True)),
                ('license_pricing', models.TextField(blank=True)),
                ('vendor_quotation_ref', models.CharField(blank=True, max_length=150)),
                ('subscription_terms', models.TextField(blank=True)),
                ('tax_gst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('cost_comparison', models.TextField(blank=True)),
                ('business_value', models.TextField(blank=True)),
                ('available_alternatives', models.TextField(blank=True)),
                ('research_notes', models.TextField(blank=True)),
                ('current_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('recommended_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(blank=True, default='INR', max_length=10)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('final_estimated_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('pricing_source', models.CharField(blank=True, max_length=200)),
                ('quote_reference', models.CharField(blank=True, max_length=150)),
                ('business_evaluation', models.TextField(blank=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='research_documents/')),
                ('is_completed', models.BooleanField(default=False)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_estimation', to='request_management.purchaserequest')),
                ('researched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_researches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
