# Generated by Django 5.2.17 on 2026-09-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0006_purchaserequest_budget_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('RESEARCH_SAVED', 'Research Saved'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SEND_BACK', 'Sent Back'), ('RESUBMIT', 'Resubmitted'), ('RECOMMEND_FINANCE', 'Recommended to Finance'), ('FINANCE_APPROVE', 'Finance Approved'), ('FINANCE_REJECT', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('MOCK_PAYMENT', 'Mock Payment Completed'), ('PAYMENT_JUSTIFICATION_SUBMITTED', 'Payment Justification Submitted'), ('PAYMENT_JUSTIFIED', 'Payment Justified'), ('TEAM_LEAD_CONFIRM', 'Team Lead Confirmed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('ADMIN_APPROVE', 'Admin Approved'), ('ADMIN_REJECT', 'Admin Rejected'), ('ADMIN_RETURN', 'Admin Returned')], max_length=60),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='new_status',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='previous_status',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='user_role',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TEAM_LEAD_SUBMITTED', 'Team Lead Submitted'), ('TEAM_LEAD_REVIEW', 'Team Lead Review'), ('MANAGER_REVIEW', 'Manager Review'), ('MANAGER_RESEARCHING', 'Manager Researching'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_RECOMMENDED', 'Finance Recommended'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_JUSTIFICATION_SUBMITTED', 'Payment Justification Submitted'), ('PAYMENT_JUSTIFIED', 'Payment Justified'), ('Pending', 'Pending (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Returned', 'Returned (Legacy)'), ('In Procurement', 'In Procurement (Legacy)')], db_index=True, default='TEAM_LEAD_REVIEW', max_length=40),
        ),
    ]
