# Generated by Django 5.2.17 on 2026-09-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0010_alter_approvalhistory_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('software_name', models.CharField(blank=True, max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('purchase_type', models.CharField(blank=True, default='New', max_length=50)),
                ('subscription_type', models.CharField(blank=True, default='Annual', max_length=50)),
                ('users_licenses', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('plan_edition', models.CharField(blank=True, max_length=150)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('manager_approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('finance_approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('actual_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gst_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('final_payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('why_required', models.TextField(blank=True)),
                ('business_purpose', models.TextField(blank=True)),
                ('who_will_use', models.TextField(blank=True)),
                ('expected_benefits', models.TextField(blank=True)),
                ('impact_if_not_purchased', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, default='Medium', max_length=50)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=255)),
                ('quote_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('purchase_url', models.CharField(blank=True, max_length=500)),
                ('selected_plan', models.CharField(blank=True, max_length=150)),
                ('purchase_remarks', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, default='Paid', max_length=50)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='justifications/invoices/')),
                ('quote_file', models.FileField(blank=True, null=True, upload_to='justifications/quotes/')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='justifications/receipts/')),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='justifications/supporting/')),
                ('team_lead_name', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('comments_remarks', models.TextField(blank=True)),
                ('confirmation_checked', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_justification', to='request_management.purchaserequest')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_justifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_justifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
