# Generated by Django 5.2.17 on 2026-09-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0011_paymentjustification'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerresearchestimation',
            name='admin_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='managerresearchestimation',
            name='estimated_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='managerresearchestimation',
            name='hardware_specs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='managerresearchestimation',
            name='quantity_licenses',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='managerresearchestimation',
            name='software_licensing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('RESEARCH_SAVED', 'Research Saved'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SEND_BACK', 'Sent Back'), ('RESUBMIT', 'Resubmitted'), ('RECOMMEND_FINANCE', 'Recommended to Finance'), ('RECOMMEND_ADMIN', 'Recommended to Admin'), ('FINANCE_RECOMMEND_ADMIN', 'Finance Recommended to Admin'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_RESEARCH', 'Finance Research'), ('COST_ESTIMATION', 'Cost Estimation Submitted'), ('FINANCE_REPORT', 'Finance Report Generated'), ('FINANCE_APPROVE', 'Finance Approved'), ('FINANCE_REJECT', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('MOCK_PAYMENT', 'Mock Payment Completed'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_JUSTIFICATION_SUBMITTED', 'Payment Justification Submitted'), ('PAYMENT_JUSTIFIED', 'Payment Justified'), ('TEAM_LEAD_CONFIRM', 'Team Lead Confirmed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('ADMIN_APPROVE', 'Admin Approved'), ('ADMIN_REJECT', 'Admin Rejected'), ('ADMIN_RETURN', 'Admin Returned'), ('ADMIN_RESEARCH', 'Admin Research Saved'), ('ADMIN_COST_ESTIMATION', 'Admin Cost Estimation Submitted')], max_length=60),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TEAM_LEAD_SUBMITTED', 'Team Lead Submitted'), ('TEAM_LEAD_REVIEW', 'Team Lead Review'), ('MANAGER_REVIEW', 'Manager Review'), ('RECOMMENDED_TO_FINANCE', 'Recommended to Finance'), ('FINANCE_RECOMMENDED', 'Finance Recommended'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_RESEARCH', 'Finance Research'), ('COST_ESTIMATION', 'Cost Estimation'), ('FINANCE_REPORT', 'Finance Report'), ('MANAGER_RESEARCHING', 'Manager Researching'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_JUSTIFICATION_SUBMITTED', 'Payment Justification Submitted'), ('PAYMENT_JUSTIFIED', 'Payment Justified'), ('RECOMMENDED_TO_ADMIN', 'Recommended to Admin'), ('FINANCE_RECOMMENDED_TO_ADMIN', 'Finance Recommended to Admin'), ('ADMIN_REVIEW', 'Admin Review'), ('ADMIN_RESEARCH', 'Admin Research'), ('ADMIN_APPROVED', 'Admin Approved'), ('Pending', 'Pending (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Returned', 'Returned (Legacy)'), ('In Procurement', 'In Procurement (Legacy)')], db_index=True, default='TEAM_LEAD_REVIEW', max_length=40),
        ),
    ]
