# Generated by Django 5.2.17 on 2026-09-28 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0013_alter_approvalhistory_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentjustification',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentjustification',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_justifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentjustification',
            name='acknowledgement_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentjustification',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('RESEARCH_SAVED', 'Research Saved'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SEND_BACK', 'Sent Back'), ('RESUBMIT', 'Resubmitted'), ('RECOMMEND_FINANCE', 'Recommended to Finance'), ('MANAGER_RECOMMEND_FINANCE', 'Manager Recommended to Finance'), ('RECOMMEND_ADMIN', 'Recommended to Admin'), ('FINANCE_RECOMMEND_ADMIN', 'Finance Recommended to Admin'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_RESEARCH', 'Finance Research'), ('COST_ESTIMATION', 'Cost Estimation Submitted'), ('FINANCE_REPORT', 'Finance Report Generated'), ('FINANCE_APPROVE', 'Finance Approved'), ('FINANCE_REJECT', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('MOCK_PAYMENT', 'Mock Payment Completed'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_JUSTIFICATION_SUBMITTED', 'Payment Justification Submitted'), ('PAYMENT_JUSTIFIED', 'Payment Justified'), ('MANAGER_VERIFIED', 'Manager Verified Justification'), ('TEAM_LEAD_ACKNOWLEDGE', 'Team Lead Acknowledged Justification'), ('REQUEST_COMPLETED', 'Request Completed'), ('TEAM_LEAD_CONFIRM', 'Team Lead Confirmed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('ADMIN_APPROVE', 'Admin Approved'), ('ADMIN_REJECT', 'Admin Rejected'), ('ADMIN_RETURN', 'Admin Returned'), ('ADMIN_RESEARCH', 'Admin Research Saved'), ('ADMIN_COST_ESTIMATION', 'Admin Cost Estimation Submitted')], max_length=60),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('TEAM_LEAD_SUBMITTED', 'Team Lead Submitted'), ('TEAM_LEAD_REVIEW', 'Team Lead Review'), ('MANAGER_REVIEW', 'Manager Review'), ('RECOMMENDED_TO_FINANCE', 'Recommended to Finance'), ('MANAGER_RECOMMENDED_TO_FINANCE', 'Manager Recommended to Finance'), ('FINANCE_RECOMMENDED', 'Finance Recommended'), ('FINANCE_REVIEW', 'Finance Review'), ('FINANCE_RESEARCH', 'Finance Research'), ('COST_ESTIMATION', 'Cost Estimation'), ('FINANCE_REPORT', 'Finance Report'), ('MANAGER_RESEARCHING', 'Manager Researching'), ('PRE_ESTIMATION_COMPLETED', 'Pre-Estimation Completed'), ('MANAGER_APPROVED', 'Manager Approved'), ('FINANCE_APPROVED', 'Finance Approved'), ('FINANCE_REJECTED', 'Finance Rejected'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('TEAM_LEAD_CONFIRMED', 'Team Lead Confirmed'), ('COMPLETED', 'Completed'), ('SENT_BACK', 'Sent Back'), ('REJECTED', 'Rejected'), ('PAYMENT_APPROVED', 'Payment Approved'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_JUSTIFICATION_SUBMITTED', 'Payment Justification Submitted'), ('PAYMENT_JUSTIFIED', 'Payment Justified'), ('MANAGER_VERIFIED', 'Manager Verified'), ('MANAGER_VERIFIED_PENDING_TEAM_LEAD_ACKNOWLEDGEMENT', 'Manager Verified - Pending Team Lead Acknowledgement'), ('TEAM_LEAD_ACKNOWLEDGED', 'Team Lead Acknowledged'), ('REQUEST_COMPLETED', 'Request Completed'), ('RECOMMENDED_TO_ADMIN', 'Recommended to Admin'), ('FINANCE_RECOMMENDED_TO_ADMIN', 'Finance Recommended to Admin'), ('ADMIN_REVIEW', 'Admin Review'), ('ADMIN_RESEARCH', 'Admin Research'), ('ADMIN_APPROVED', 'Admin Approved'), ('Pending', 'Pending (Legacy)'), ('Approved', 'Approved (Legacy)'), ('Returned', 'Returned (Legacy)'), ('In Procurement', 'In Procurement (Legacy)')], db_index=True, default='TEAM_LEAD_REVIEW', max_length=60),
        ),
    ]
