# Generated by Django 5.2.17 on 2026-09-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0014_paymentjustification_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Purchase Request', 'verbose_name_plural': 'Purchase Requests'},
        ),
    ]
