# Generated by Django 5.2.17 on 2026-09-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0015_alter_purchaserequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Purchase Request', 'verbose_name_plural': 'Purchase Requests'},
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='original_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_descendants', to='request_management.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='request_management.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='renewal_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_operation',
            field=models.CharField(choices=[('NEW', 'New Purchase'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade')], default='NEW', max_length=20),
        ),
    ]
