# Generated by Django 5.2.17 on 2026-10-01 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0017_performance_indexes'),
        ('users', '0002_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approvalhistory',
            name='approv_hist_req_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='approvalhistory',
            name='approv_hist_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='pr_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='pr_approval_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='pr_dept_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='pr_created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaserequest',
            name='pr_assigned_tl_idx',
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', '-created_at'], name='pr_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by', 'status', '-created_at'], name='pr_createdby_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['flow_type', 'status'], name='pr_flowtype_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['current_approval_level', '-created_at'], name='pr_approval_level_idx'),
        ),
    ]
