# Generated by Django 5.2.17 on 2026-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='software_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
