# Generated by Django 5.1.15 on 2026-10-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0019_add_software_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='managerresearchestimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentjustification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='current_stage',
            field=models.IntegerField(choices=[(0, 'Create Request'), (1, 'Manager Approval'), (2, 'Finance Approval'), (3, 'Admin Approval'), (4, 'RFQ Sent / Pre-Estimation Completed'), (5, 'Vendor Quotes Received / Manager Approved'), (6, 'Product Order / Finance Review'), (7, 'Delivery / Finance Approved'), (8, 'Verification / Payment Completed'), (9, 'Payment / Team Lead Confirmation'), (10, 'Request Completed')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='justification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='preferred_vendor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_operation',
            field=models.CharField(default='CREATE', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
