# Generated by Django 5.2.17 on 2026-09-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification_management', '0001_initial'),
        ('request_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='request_management.purchaserequest'),
        ),
    ]
