# Generated by Django 4.2.17 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_management', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_cef831_idx'),
        ),
    ]
