# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.CharField(default='2026', max_length=10)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin')], max_length=20)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiscal_year', models.CharField(default='2026', max_length=10)),
            ],
        ),
    ]
