# Generated by Django 5.2.17 on 2026-09-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='users.department'),
        ),
        migrations.AddField(
            model_name='budgetlimit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_limits', to='users.department'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together={('department', 'fiscal_year')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together={('role', 'department', 'fiscal_year')},
        ),
    ]
