# Generated by Django 4.2.17 on 2026-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
